name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  pest-tests:
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2.28
          tools: composer:v2
          coverage: none

      - name: Prepare Storage Directories
        run: |
          mkdir -p storage/framework/views
          mkdir -p storage/framework/cache
          mkdir -p bootstrap/cache

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Setup Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env
          php artisan migrate --no-interaction

      - name: Run Pest
        run: ./vendor/bin/pest